Add Smith-Waterman native bindings
broadinstitute/gatk-native-bindings pull request #10
Opened 2017-06-21 14:29 UTC by gspowley

Add native bindings for Smith-Waterman.

2017-07-05 17:14 UTC, lbergelson requested changes

2017-07-05 17:14 UTC, lbergelson commented on src/main/java/org/broadinstitute/gatk/nativebindings/smithwaterman/SWAlignmentResult.java
> +    public String cigar;
make these final and initialize in the constructor

2017-07-05 17:14 UTC, lbergelson commented on src/main/java/org/broadinstitute/gatk/nativebindings/smithwaterman/SWAlignerNativeBinding.java
> +     * Print final profiling information from native code and close any resources.
this should just close the resources

2017-07-05 17:14 UTC, lbergelson commented on src/main/java/org/broadinstitute/gatk/nativebindings/smithwaterman/SWAlignerNativeArguments.java
> +    public int w_match;
these should be final and initialized in a constructor

2017-07-05 17:26 UTC, lbergelson commented on src/main/java/org/broadinstitute/gatk/nativebindings/smithwaterman/SWAlignerNativeBinding.java
> +    void done();
if we don't need this now, lets remove it and add it back if we do

2017-07-05 17:29 UTC, lbergelson commented on src/main/java/org/broadinstitute/gatk/nativebindings/smithwaterman/SWAlignerNativeArguments.java
> +    public int w_mismatch;
We should enforce any constraints on these in the constructor.

2017-07-07 14:27 UTC, pnvaidya commented on src/main/java/org/broadinstitute/gatk/nativebindings/smithwaterman/SWAlignerNativeArguments.java
> +    public int w_mismatch;
I tried to add constraints but I cannot use the Utils class which original code uses. Wondering if we can enforce constraints in base class in GATK as opposed to native bindings? thoughts?

2017-07-07 14:54 UTC, lbergelson commented on src/main/java/org/broadinstitute/gatk/nativebindings/smithwaterman/SWAlignerNativeArguments.java
> +    public int w_mismatch;
@pnvaidya Just use if statements and throw IllegalArgumentException.  That's all the validation methods do.

2017-07-07 15:09 UTC, pnvaidya commented on src/main/java/org/broadinstitute/gatk/nativebindings/smithwaterman/SWAlignerNativeArguments.java
> +    public int w_mismatch;
Ok. Done.

2017-07-07 18:39 UTC, lbergelson commented
closing since these changes were completed in #11

2017-07-07 18:39 UTC, closed without merging